In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt #import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf

### Importing Data

In [2]:
train_data = pd.read_csv(r'/Users/vidhanjain/desktop/Jupiter/digit-recognizer/train.csv')
test_data = pd.read_csv(r'/Users/vidhanjain/desktop/Jupiter/digit-recognizer/test.csv')
combine = [train_data,test_data]
train_data.shape

(42000, 785)

In [3]:
train_data.head()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
test_data.head()

,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
train_data.describe()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
count,42000.000000,42000.0,42000.0,42000.0,42000.0,42000.0,42000.0,42000.0,42000.0,42000.0,...,42000.000000,42000.000000,42000.000000,42000.00000,42000.000000,42000.000000,42000.0,42000.0,42000.0,42000.0
mean,4.456643,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.219286,0.117095,0.059024,0.02019,0.017238,0.002857,0.0,0.0,0.0,0.0
std,2.887730,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,6.312890,4.633819,3.274488,1.75987,1.894498,0.414264,0.0,0.0,0.0,0.0
min,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.0,0.0,0.0
25%,2.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.0,0.0,0.0
50%,4.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.0,0.0,0.0
75%,7.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.0,0.0,0.0
max,9.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,254.000000,254.000000,253.000000,253.00000,254.000000,62.000000,0.0,0.0,0.0,0.0

#### Data Split

In [6]:
data_train = train_data.iloc[:31000]
data_dev = train_data.iloc[31000:]

In [7]:
X_train = data_train.iloc[:,1:].to_numpy()
y_train = data_train[['label']].to_numpy()
X_dev = data_dev.iloc[:,1:].to_numpy()
y_dev = data_dev[['label']].to_numpy()
X_test = test_data.to_numpy()

### Building the Model

In [8]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(128,activation='relu'),
    tf.keras.layers.Dense(10)
])

In [9]:
model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

### Training the Model

In [10]:
model.fit(X_train, y_train, epochs=10)

2022-01-28 11:40:35.544774: I tensorflow/core/platform/cpu_feature_guard.cc:145] This TensorFlow binary is optimized with Intel(R) MKL-DNN to use the following CPU instructions in performance critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in non-MKL-DNN operations, rebuild TensorFlow with the appropriate compiler flags.
2022-01-28 11:40:35.545147: I tensorflow/core/common_runtime/process_util.cc:115] Creating new thread pool with default inter op setting: 4. Tune using inter_op_parallelism_threads for best performance.

Train on 31000 samples
Epoch 1/10
31000/31000 [==============================] - 7s 215us/sample - loss: 4.8788 - accuracy: 0.8414
Epoch 2/10
31000/31000 [==============================] - 6s 188us/sample - loss: 0.5543 - accuracy: 0.8823
Epoch 3/10
31000/31000 [==============================] - 6s 188us/sample - loss: 0.3737 - accuracy: 0.9119
Epoch 4/10
31000/31000 [==============================] - 6s 184us/sample - loss: 0.3182 - accuracy: 0.9249
Epoch 5/10
31000/31000 [==============================] - 6s 187us/sample - loss: 0.2642 - accuracy: 0.9342
Epoch 6/10
31000/31000 [==============================] - 6s 188us/sample - loss: 0.2523 - accuracy: 0.9380
Epoch 7/10
31000/31000 [==============================] - 7s 236us/sample - loss: 0.2218 - accuracy: 0.9428
Epoch 8/10
31000/31000 [==============================] - 8s 251us/sample - loss: 0.2144 - accuracy: 0.9465
Epoch 9/10
31000/31000 [==============================] - 9s 283us/sample - loss: 0.2106 - accuracy: 0.9465
Epoch 10/10
31000/31000 [==============================] - 6s 183us/sample - loss: 0.1975 - accuracy: 0.9514

In [11]:
dev_loss, dev_acc = model.evaluate(X_dev,  y_dev, verbose=2)

print('\nTest accuracy:', dev_acc)

11000/1 - 1s - loss: 0.1952 - accuracy: 0.9385

Test accuracy: 0.93845457

### Making Predictions

In [12]:
probability_model = tf.keras.Sequential([model, 
                                         tf.keras.layers.Softmax()])
predictions = probability_model.predict(X_test)

In [13]:
predictions[0]

array([0.0000000e+00, 1.7083827e-19, 1.0000000e+00, 1.8999991e-15,
       0.0000000e+00, 3.2518084e-29, 1.9093695e-25, 2.7833205e-28,
       5.8065672e-26, 0.0000000e+00], dtype=float32)

In [17]:
final_predictions = np.zeros([np.size(X_test,axis=0),1])
for i in range(0,np.size(X_test,axis=0)):
    final_predictions[i] = np.argmax(predictions[i])

In [18]:
DF = pd.DataFrame(final_predictions)
DF.to_csv("submission.csv")